export const SITE = {
  website: "https://blog.alishot.dev/",
  author: "Álisson Melquíades",
  profile: "https://alishot.dev/",
  desc: "Backup mental de alguém que é viciado em aprender coisas novas.",
  title: "Alishot Labs",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Editar página",
    url: "https://github.com/alissonrms/blog/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "pt-BR",
  timezone: "America/Sao_Paulo",
} as const;
